### ISSUE TITLE
Use objects instead of arrays for projects, sections?

### ISSUE THREAD

**Issue by jplatte** [haecker-felix/hebbot#66]
Since every section and project seems to have a sort of id ("name") in addition to its title, is this not an obvious place to use an object instead and change

```toml
[[section]]
name = "foo"
title = "Foo"
```

to

```toml
[section.foo]
title = "Foo"
```

?
